DROP DATABASE IF EXISTS news_site;
CREATE DATABASE news_site;
USE news_site;

CREATE TABLE ROLES(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(20) NOT NULL
);

CREATE TABLE COMMENTS(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Comment VARCHAR(255) NOT NULL,
    User_Id INT NOT NULL,
    News_Id INT NOT NULL,
    CONSTRAINT FOREIGN KEY(User_Id) REFERENCES USERS(Id),
    CONSTRAINT FOREIGN KEY(News_Id) REFERENCES NEWS(Id)
);

CREATE TABLE USERS(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Birthdate YEAR NOT NULL,
    Gender ENUM("Male", "Female") NOT NULL
);

CREATE TABLE USERS_ROLES(
	User_Id INT NOT NULL,
    Role_Id INT NOT NULL,
	CONSTRAINT FOREIGN KEY(User_Id) REFERENCES USERS(Id),
    CONSTRAINT FOREIGN KEY(Role_Id) REFERENCES ROLES(Id),
    PRIMARY KEY(User_Id, Role_Id)
);

CREATE TABLE CATEGORIES(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE NEWS(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(50),
	Content VARCHAR(255),
    Editor_Id INT NOT NULL,
    Category_Id INT NOT NULL,
    CONSTRAINT FOREIGN KEY(Editor_Id) REFERENCES USERS(Id),
    CONSTRAINT FOREIGN KEY(Category_Id) REFERENCES CATEGORIES(Id)
);

CREATE TABLE MEDIA(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Type_Media VARCHAR(50),
    News_Id INT NOT NULL,
    Path_Media VARCHAR(255) NOT NULL,
    CONSTRAINT FOREIGN KEY(Category_Id) REFERENCES NEWS(Id)
);



